// ============================================================
// Shoe Data — AUTO-GENERATED by generate-shoe-data.js
// Generated: 2026-05-24T11:47:53.128Z
// Total shoes: 111
// ============================================================
// To add new shoes:
//   1. Create shoes/{id}/ folder with images + {id}.txt
//   2. Run: node generate-shoe-data.js
// ============================================================

const SHOE_DATA = {
    1: {
        images: [
            'i1778950178206_5303_0_1.jpg',
            'i1778950194293_3095_0_7.jpg',
            'i1778950194294_209_0_8.jpg',
            'i1778950194299_2187_0_5.jpg',
            'i1778950207735_8131_0_5.jpg',
            'i1778950207736_8322_0_7.jpg',
            'i1778950221054_1301_0_8.jpg'
        ],
        desc: 'FILA MUFFIN WE: Stylish, unique, minimalist, trendy, versatile, and comfortable low-top casual sneakers'
    },
    2: {
        images: [
            'A01.jpg',
            'A02.jpg',
            'A03.jpg',
            'A04.jpg',
            'A05.jpg',
            'A06.jpg',
            'A07.jpg',
            'A08.jpg',
            'A09.jpg',
            'i1776191930407_1563_0_4.jpg'
        ],
        desc: 'Authentic AF1 Air Force 1 New Collaboration Model Unisex Casual Street Style Black Sports Couple\'s Style Low-Top Sneakers'
    },
    3: {
        images: [
            'a1776108323443_2464.jpg',
            'a1776108323616_2541.jpg',
            'a1776108323789_7161.jpg',
            'a1776108372100_0488.jpg',
            'a1776108372305_3367.jpg',
            'a1776108372340_7526.jpg',
            'a1776108380732_3073.jpg',
            'a1776108380760_6577.jpg',
            'a1776108380955_7772.jpg'
        ],
        desc: 'Premium quality sneakers with modern design and superior comfort for everyday wear.'
    },
    4: {
        images: [
            'a1776281145759_8760.jpg',
            'a1776281145928_6474.jpg',
            'a1776281145938_8012.jpg',
            'a1776281146047_8822.jpg',
            'a1776281146195_3700.jpg',
            'a1776281147878_0185.jpg',
            'a1776281147878_4530.jpg',
            'a1776281147917_8517.jpg',
            'a1776281148013_6568.jpg'
        ],
        desc: '$85\nAdidas Originals Samba OG: A versatile, low-top casual sneaker with a classic soccer-inspired design'
    },
    5: {
        images: [
            'a1776367645512_6882.jpg',
            'a1776367645706_1241.jpg',
            'a1776367646020_0140.jpg',
            'a1776367646270_0870.jpg',
            'a1776367646306_3665.jpg',
            'a1776367647470_8711.jpg',
            'a1776367647481_2561.jpg',
            'a1776367647566_6221.jpg',
            'a1776367647669_4781.jpg'
        ],
        desc: '$87\nAuthentic Original Shoes: Stream-Crossing Shoes, Water-Crossing Shoes, Hiking, Camping, Casual, Sports—Unisex Style'
    },
    6: {
        images: [
            'ad1.jpg',
            'ad2.jpg',
            'ad3.jpg',
            'ad4.jpg',
            'ad5.jpg',
            'ad6.jpg',
            'ad7.jpg',
            'ad8.jpg',
            'ad9.jpg'
        ],
        desc: '$85\nNew BASF “True Pop” Popcorn EDGE Cushioned Running Shoes for Men and Women: Mesh, Casual, Breathable, and Sporty'
    },
    7: {
        images: [
            'i1733772404_1239_8.jpg',
            'i1733772404_1513_6.jpg',
            'i1733772404_2507_7.jpg',
            'i1733772404_2627_1.jpg',
            'i1733772404_4011_2.jpg',
            'i1733772404_632_3.jpg',
            'i1733772404_7534_4.jpg',
            'i1733772404_8057_0.jpg',
            'i1733772404_8766_5.jpg'
        ],
        desc: '$87\nAuthentic New Pegasus 42 Men\'s and Women\'s Shoes: Mesh Upper, Thin Sole, Breathable, Shock-Absorbing Running Shoes with Soft Soles for Casual and Athletic Wear'
    },
    8: {
        images: [
            'i1761236437_1217_8.jpg',
            'i1761236437_1607_1.jpg',
            'i1761236437_7960_7.jpg',
            'i1761236437_8031_6.jpg',
            'i1761236437_8232_5.jpg',
            'i1761236437_8992_0.jpg',
            'i1761236437_899_2.jpg',
            'i1761236437_9142_3.jpg',
            'i1761236437_9540_4.jpg'
        ],
        desc: '$86\nBest-Selling AF1 Air Force 1: Versatile All-White Low-Top Sneakers for Men and Women—Casual Couple Shoes, Same Style as the Classic White Sneakers'
    },
    9: {
        images: [
            'i1748886193392_1183_0_0.jpg',
            'i1748886286593_9109_0_0.jpg',
            'i1748886327299_2728_0_0.jpg',
            'i1748886353492_5816_0_0.jpg',
            'i1748886353562_1031_0_2.jpg',
            'i1748886353564_4390_0_8.jpg',
            'i1748886353564_668_0_5.jpg',
            'i1748886353564_8792_0_7.jpg',
            'i1748886368557_5578_0_4.jpg',
            'i1748886445696_1746_0_4.jpg'
        ],
        desc: '$83\nCoconut Shoes 350V2 Starry Sky Large Size Breathable Angel Ultra-Soft Sole High-Quality Unisex Casual Sports Fashion Sneakers'
    },
    10: {
        images: [
            'i1748886368558_4617_0_3.jpg',
            'i1748886368560_8561_0_6.jpg',
            'i1748886368565_1976_0_1.jpg',
            'i1748886396625_2346_0_7.jpg',
            'i1748886407932_6345_0_8.jpg',
            'i1748886407973_2178_0_1.jpg',
            'i1748886407973_5038_0_4.jpg',
            'i1748886407974_2131_0_0.jpg',
            'i1748886407975_7450_0_5.jpg',
            'i1748886428834_3569_0_3.jpg',
            'i1748886428835_2506_0_6.jpg',
            'i1748886428835_7112_0_2.jpg',
            'i1748886437499_1434_0_0.jpg'
        ],
        desc: '$83\nMen\'s Authentic 350 Campus-Style Coconut Shoes in Starry Sky Gray and Orange—Breathable, Casual, and Trendy Summer Sneakers'
    },
    11: {
        images: [
            'i1755706543925_4131_0_0.jpg',
            'i1755706543926_2700_0_4.jpg',
            'i1755706543926_4303_0_7.jpg',
            'i1755706588116_9042_0_0.jpg',
            'i1755706588116_9759_0_7.jpg',
            'i1755706588117_8343_0_4.jpg',
            'i1774369758414_3601_0_0.jpg'
        ],
        desc: '$95\nAdidas CLIMACOOL VENTO 4.0 Breathable Running Shoes for Men and Women'
    },
    12: {
        images: [
            'i1774370437754_8978_0_0.jpg',
            'i1774370437832_5599_0_6.jpg',
            'i1774370438295_1597_0_7.jpg',
            'i1774370438798_9955_0_8.jpg',
            'i1774370439522_1304_0_4.jpg'
        ],
        desc: '$88\nCool Dads\' Shoes: Men\'s Height-Increasing Chunky-Soled Vintage Distressed Casual Shoes for Couples – Women\'s 2026 Spring/Summer New Arrivals'
    },
    13: {
        images: [
            '02.jpg',
            '03.jpg',
            '04.jpg',
            '05.jpg',
            '06.jpg',
            '07.jpg',
            '08.jpg',
            '09.jpg',
            'i1774370439550_1625_0_2.jpg',
            'i1774370440197_1234_0_3.jpg',
            'i1774370440234_7634_0_5.jpg'
        ],
        desc: '$85\nNike Air Force 1 \'07 Low Collaboration Air Force 1 Low-Top Sneakers Casual Shoes Stitched Cuff (Highly Complex Craftsmanship) Original Last and Cardboard, Original Shoe Box, Custom Hardware'
    },
    14: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg'
        ],
        desc: '$88\nNike Air Jordan 1 Low Custom Colorway  \nCustom AJ Collaboration – High-End Custom Low-Top Retro Sneakers\n#CustomShoeBox Authentic factory quality, ultra-clean finish, cleanly cut leather with no frayed edges, perfect details'
    },
    15: {
        images: [
            'i1774974810294_2228_0_7.jpg',
            'i1774974863065_5765_0_7.jpg',
            'i1774974875292_4455_0_7.jpg',
            'i1774974907669_4134_0_7.jpg',
            'i1774975003228_3773_0_7.jpg',
            'i1774975070309_3417_0_7.jpg',
            'i1774975083990_9711_0_7.jpg',
            'i1774975097451_9414_0_7.jpg',
            'i1774975111592_192_0_7.jpg',
            'i1774975124588_2876_0_7.jpg',
            'i1774975165364_5142_0_8.jpg',
            'i1774975165469_7443_0_6.jpg',
            'i1774975165471_6873_0_5.jpg'
        ],
        desc: '$86\nFILA 1S Mars 25 Fall/Winter Women\'s Shoes: Retro-Style Fashionable Sneakers; Men\'s Cushioned, Breathable Running Shoes'
    },
    16: {
        images: [
            'i1774974894175_1294_0_0.jpg',
            'i1774974894175_5272_0_8.jpg',
            'i1774974894175_5435_0_4.jpg',
            'i1774974894176_1092_0_3.jpg',
            'i1774974894176_4454_0_5.jpg',
            'i1774974894519_3115_0_1.jpg',
            'i1774974894521_952_0_6.jpg',
            'i1774974894521_9990_0_7.jpg',
            'i1774974894523_8128_0_2.jpg'
        ],
        desc: '$85\nFILA Mars Women\'s Gray/Black Lightweight Cushioned Anti-Slip Durable Casual Sneakers F12W322109FFA'
    },
    17: {
        images: [
            'i1775316310287_4403_0_7.jpg',
            'i1775316341996_705_0_7.jpg',
            'i1775316360947_261_0_7.jpg',
            'i1775316383005_6954_0_7.jpg',
            'i1775316407875_9275_0_7.jpg',
            'i1775316428567_2635_0_7.jpg',
            'i1775316455368_8281_0_7.jpg',
            'i1775316477610_6976_0_7.jpg',
            'i1775316499410_4166_0_7.jpg'
        ],
        desc: '$85\nNew Collaboration: Versatile, Authentic React Infinity Run 3 Air-Cushioned Running Shoes—Breathable, Lightweight, and Shock-Absorbing DZ'
    },
    18: {
        images: [
            'i1775582689690_2004_0_1.jpg',
            'i1775582689696_2388_0_0.jpg',
            'i1775582689709_1060_0_5.jpg',
            'i1775582689711_490_0_2.jpg',
            'i1775582689736_3831_0_3.jpg',
            'i1775582691040_2478_0_6.jpg',
            'i1775582691041_3811_0_7.jpg',
            'i1775582691076_5954_0_8.jpg',
            'i1775582691085_3852_0_4.jpg'
        ],
        desc: '$83\nAuthentic New AF1 Year of the Horse Limited Edition Air Force 1 with Auspicious Cloud Embroidery: A Versatile, Trendy Must-Have Sneaker for the New Year'
    },
    19: {
        images: [
            'i1775247420758_4830_0_4.jpg',
            'i1775247449314_9638_0_1.jpg',
            'i1775664656394_6455_0_7.jpg',
            'i1775664675171_5360_0_7.jpg',
            'i1775664696583_3002_0_7.jpg',
            'i1775664715311_3353_0_7.jpg',
            'i1775664736513_1425_0_7.jpg',
            'i1775664753975_1491_0_7.jpg',
            'i1775664772766_2755_0_7.jpg',
            'i1775664792433_6600_0_7.jpg'
        ],
        desc: '$85\nAdidas Official Authentic ORIGINALS ADIMATIC Unisex Sports Sneakers ID0999'
    },
    20: {
        images: [
            'i1775664814047_9871_0_7.jpg',
            'i1775664888124_3183_0_3.jpg',
            'i1775664888354_8341_0_1.jpg',
            'i1775664888356_6531_0_2.jpg',
            'i1775664888405_6542_0_4.jpg',
            'i1775664888420_8557_0_8.jpg',
            'i1775664890113_4639_0_7.jpg',
            'i1775664890120_9497_0_0.jpg',
            'i1775664890155_2452_0_5.jpg',
            'i1775664890164_4545_0_6.jpg'
        ],
        desc: '$86\nAdidas Casual Shoes for Men and Women: New Fall Collection – Trefoil Sneakers, Retro Shark-Print Sneakers, and Skate Shoes'
    },
    21: {
        images: [
            'i1775665037744_4993_0_7.jpg',
            'i1775665054257_9852_0_7.jpg',
            'i1775665071757_5425_0_7.jpg',
            'i1775665090658_676_0_7.jpg',
            'i1775665108609_6400_0_7.jpg',
            'i1775665127515_4152_0_7.jpg',
            'i1775665153784_5786_0_7.jpg',
            'i1775665170582_2752_0_7.jpg',
            'i1775665388182_1603_0_6.jpg',
            'i1775665388183_5451_0_2.jpg'
        ],
        desc: '$87\nNew Authentic Vaporfly Next% 3 Marathon Racing Shoes: Unisex, Breathable, and Cushioned Running Shoes'
    },
    22: {
        images: [
            'i1775665388184_1773_0_0.jpg',
            'i1775665388185_5419_0_5.jpg',
            'i1775665388370_7319_0_8.jpg',
            'i1775665389094_6919_0_1.jpg',
            'i1775665389095_2426_0_4.jpg',
            'i1775665389095_7986_0_3.jpg',
            'i1775665389359_9897_0_7.jpg'
        ],
        desc: '$86\nNew Casual Sneakers: Versatile Men\'s Marathon Running Shoes'
    },
    23: {
        images: [
            'i1775670072151_438_0_1.jpg',
            'i1775670072180_206_0_4.jpg',
            'i1775670072183_7114_0_5.jpg',
            'i1775670072209_9936_0_3.jpg',
            'i1775670073545_7168_0_8.jpg',
            'i1775670073574_173_0_2.jpg',
            'i1775670073598_8661_0_0.jpg',
            'i1775670073619_4547_0_6.jpg',
            'i1775908696921_5213_0_0.jpg',
            'i1775923720103_8043_0_0.jpg'
        ],
        desc: '$85\nPure Original Fly6 Marathon Carbon Plate Running Shoes: Mesh Upper, Breathable, Shock-Absorbing, Unisex, Casual, Student, Training'
    },
    24: {
        images: [
            'i1775925441246_5242_0_7.jpg',
            'i1775925441294_8432_0_8.jpg',
            'i1775925441303_3333_0_1.jpg',
            'i1775925472781_314_0_8.jpg',
            'i1775925473640_4046_0_7.jpg',
            'i1775925473659_450_0_1.jpg',
            'i1775925484830_6980_0_8.jpg',
            'i1775925485407_7160_0_7.jpg',
            'i1775925485415_6676_0_1.jpg'
        ],
        desc: '$85\nAuthentic ML NY Yankees Elevated Sneakers: Unisex Casual Couple\'s Versatile White Sneakers with Chunky Soles'
    },
    25: {
        images: [
            'i1776096083006_4959_0_5.jpg',
            'i1776096083007_1351_0_3.jpg',
            'i1776096083007_3102_0_0.jpg',
            'i1776096083007_3387_0_7.jpg',
            'i1776096083007_5679_0_2.jpg',
            'i1776096083961_6020_0_8.jpg',
            'i1776096083962_751_0_4.jpg',
            'i1776096083963_1660_0_1.jpg',
            'i1776096083963_321_0_6.jpg'
        ],
        desc: '$87\nNew Authentic Yankees NY High-Top Sneakers: Height-Enhancing Retro Chunky-Sole Sports Shoes for Men and Women—Comfortable and Versatile'
    },
    26: {
        images: [
            'i1776191928059_9359_0_3.jpg',
            'i1776191928068_2600_0_8.jpg',
            'i1776191928173_2017_0_1.jpg',
            'i1776191928311_9981_0_2.jpg',
            'i1776191928363_2402_0_0.jpg',
            'i1776191930505_6454_0_5.jpg',
            'i1776191930538_2355_0_6.jpg',
            'i1776191930567_8237_0_7.jpg'
        ],
        desc: '$87\nAdidas Sneakers: Men\'s and Women\'s 2025 Fall/Winter New Arrivals—Running Shoes, Mecha-Style Sneakers, and Chunky-Soled Casual Shoes'
    },
    27: {
        images: [
            'i1776269788168_766_0_0.jpg',
            'i1776269788169_7128_0_8.jpg',
            'i1776269788169_7229_0_7.jpg',
            'i1776269788169_7776_0_1.jpg',
            'i1776269788169_9974_0_4.jpg',
            'i1776269790065_4263_0_5.jpg',
            'i1776269790067_3634_0_3.jpg',
            'i1776269790067_3861_0_6.jpg',
            'i1776269790068_1281_0_2.jpg'
        ],
        desc: '$88\nMTE ULTRARANGE NEOVR3 Comfortable Low-Top Classic Black and White Unisex Retro Casual Sneakers with Campus Style'
    },
    28: {
        images: [
            'i1776270584609_1398_0_2.jpg',
            'i1776270584609_1669_0_8.jpg',
            'i1776270584610_4637_0_0.jpg',
            'i1776270584610_8725_0_1.jpg',
            'i1776270584611_435_0_7.jpg',
            'i1776270585484_1787_0_3.jpg',
            'i1776270585485_302_0_4.jpg',
            'i1776270585485_5765_0_5.jpg',
            'i1776270585486_8533_0_6.jpg'
        ],
        desc: '$88\nAuthentic Adidas Three Leaves Women\'s Sneakers: Classic Shell-Toe 2nd Generation Casual Sneakers JH9977'
    },
    29: {
        images: [
            'i1776271102504_2947_0_4.jpg',
            'i1776271102504_3490_0_5.jpg',
            'i1776271102505_7780_0_6.jpg',
            'i1776271102507_4135_0_1.jpg',
            'i1776271102507_4603_0_2.jpg',
            'i1776271104273_1059_0_0.jpg',
            'i1776271104274_526_0_7.jpg',
            'i1776271104274_5681_0_8.jpg',
            'i1776271104274_592_0_3.jpg'
        ],
        desc: '$85\nNew Classic AF1 Air Force 1 Floral Black Unisex Low-Top Versatile Casual Sneakers'
    },
    30: {
        images: [
            'i1776278286411_4035_0_3.jpg',
            'i1776278286412_6895_0_4.jpg',
            'i1776278286414_8115_0_6.jpg',
            'i1776278289816_3414_0_1.jpg',
            'i1776278289825_1236_0_2.jpg',
            'i1776278289828_7813_0_7.jpg',
            'i1776278291636_1503_0_5.jpg',
            'i1776278291641_9515_0_0.jpg',
            'i1776278291645_7164_0_8.jpg'
        ],
        desc: '$87\nMLB Shoes: Unisex Couple\'s Checkered Retro Sneakers, Casual Chunky-Soled Sneakers, Spring/Summer 2026 New Arrival 3ASXM046N'
    },
    31: {
        images: [
            'i1776278419903_4629_0_4.jpg',
            'i1776278419903_6445_0_3.jpg',
            'i1776278419903_7640_0_6.jpg',
            'i1776278420920_755_0_8.jpg',
            'i1776278420921_5313_0_0.jpg',
            'i1776278420921_7791_0_5.jpg',
            'i1776278424478_5984_0_1.jpg',
            'i1776278424482_8285_0_2.jpg',
            'i1776278424486_8585_0_7.jpg'
        ],
        desc: '$87\n[Product Details] New Authentic Air Force 1 “Flowing Sand” Cream-Yellow Unisex Low-Top Casual Sneakers'
    },
    32: {
        images: [
            'i1776341460533_5969_0_0.jpg',
            'i1776362453083_1734_0_6.jpg',
            'i1776362453130_733_0_3.jpg',
            'i1776362453146_2221_0_2.jpg',
            'i1776362453147_3368_0_0.jpg',
            'i1776362453181_1339_0_4.jpg',
            'i1776362454011_1511_0_1.jpg',
            'i1776362454042_8597_0_8.jpg',
            'i1776362454047_3441_0_5.jpg',
            'i1776362454053_1374_0_7.jpg'
        ],
        desc: '$88\n26 Latest AJ1 Mint Blue Low-Top Sneakers for Men and Women: Casual, Fashionable, Comfortable, and Versatile Sports Shoes, Basketball Shoes, and Skate Shoes'
    },
    33: {
        images: [
            'i1776362627541_122_0_0.jpg',
            'i1776362627583_8322_0_5.jpg',
            'i1776362627585_6031_0_4.jpg',
            'i1776362627590_3846_0_2.jpg',
            'i1776362627604_4880_0_1.jpg',
            'i1776362628387_2461_0_3.jpg',
            'i1776362628540_8993_0_7.jpg',
            'i1776362628554_4040_0_8.jpg',
            'i1776362628563_7712_0_6.jpg'
        ],
        desc: '$88\nNike Women\'s Spring 2026 New Arrival V2K RUN: Versatile Retro Dad Sneakers for Sports and Casual Wear'
    },
    34: {
        images: [
            'i1776748600819_6945_0_4.jpg',
            'i1776748648920_6742_0_5.jpg',
            'i1776748650014_4751_0_4.jpg',
            'i1777235492894_5608_0_3.jpg',
            'i1777235494303_1130_0_2.jpg',
            'i1778605782841_9538_0_7.jpg',
            'i1778605797879_6944_0_1.jpg',
            'i1778605797882_9120_0_7.jpg'
        ],
        desc: '$86\nNike Sneakers: The J.Crew x Nike Killshot II Leather collaboration features an off-white leather upper accented with multicolored Swoosh logos and a multicolored natural rubber outsole, exuding a strong retro vibe.'
    },
    35: {
        images: [
            'i1776970369782_4745_0_5.jpg',
            'i1776970369801_7988_0_1.jpg',
            'i1776970369848_7135_0_3.jpg',
            'i1776970370016_8066_0_2.jpg',
            'i1776970370018_5827_0_7.jpg',
            'i1776970371230_2262_0_0.jpg',
            'i1776970371241_6048_0_4.jpg',
            'i1776970371289_7649_0_6.jpg',
            'i1776970371351_4761_0_8.jpg'
        ],
        desc: '$85\n2026 New Arrival: Light Luxury White Sneakers—Breathable, Versatile Men\'s Chunky-Soled Casual Shoes (Korean-Style High-End Sneakers)'
    },
    36: {
        images: [
            'i1777490394184_8517_0_0.jpg',
            'i1777490394204_2180_0_7.jpg',
            'i1777490394406_8251_0_5.jpg',
            'i1777490394560_7591_0_2.jpg',
            'i1777490394599_1394_0_8.jpg',
            'i1777490395508_721_0_1.jpg',
            'i1777490395598_656_0_6.jpg',
            'i1777490395663_3266_0_3.jpg',
            'i1777490395700_8569_0_4.jpg'
        ],
        desc: '$88\nNew Arrival: Chunky-Soled Sneakers for Height Enhancement – Trendy Couple\'s Shoes, Casual White Sneakers, Unisex Fashionable “Bread” Sneakers'
    },
    37: {
        images: [
            'i1777825237206_9876_0_7.jpg',
            'i1777825254619_9142_0_7.jpg',
            'i1777825266569_1898_0_7.jpg',
            'i1777825279459_6225_0_7.jpg',
            'i1777825290614_7552_0_7.jpg',
            'i1777825290616_323_0_8.jpg',
            'i1777825290618_53_0_4.jpg',
            'i1777825290618_7340_0_2.jpg',
            'i1777825290618_7560_0_1.jpg',
            'i1777825290995_2823_0_6.jpg',
            'i1777825290998_3216_0_3.jpg',
            'i1777825291000_5182_0_5.jpg',
            'i1777825291000_6269_0_0.jpg'
        ],
        desc: '$87\nNew Challenger Anti-Slip Running Shoes: Shock-Absorbing Spring Sneakers, Lightweight and Breathable for Outdoor Running - Hokka'
    },
    38: {
        images: [
            'i1777825302835_5264_0_7.jpg',
            'i1777825342151_9092_0_6.jpg',
            'i1777825342152_4691_0_10.jpg',
            'i1777825342153_6734_0_13.jpg',
            'i1777825342418_7525_0_12.jpg',
            'i1777825342421_3962_0_7.jpg',
            'i1777825342421_9584_0_11.jpg',
            'i1777825342699_3814_0_9.jpg',
            'i1777825342700_1988_0_8.jpg'
        ],
        desc: '$88\nChallenger 7 All-Terrain Outdoor Trail Running Shoes for Men and Women: Non-Slip, Durable, Breathable Mesh Casual Running Shoes'
    },
    39: {
        images: [
            'i1778356608639_6849_0_0.jpg',
            'i1778356624610_3651_0_0.jpg',
            'i1778356644072_3060_0_0.jpg',
            'i1778356662143_7688_0_0.jpg',
            'i1778357106217_979_0_7.jpg'
        ],
        desc: '$85\nHigh-Quality New Sprint Sister Women\'s Shoes: Comfortable, Snug-Fitting Summer Low-Top Casual Sneakers IB7102-100'
    },
    40: {
        images: [
            'i1778357106217_1033_0_8.jpg',
            'i1778357106220_9076_0_2.jpg',
            'i1778357107312_2145_0_1.jpg',
            'i1778357107312_3239_0_6.jpg',
            'i1778357107317_8154_0_0.jpg',
            'i1778357108492_7471_0_4.jpg',
            'i1778357108496_2570_0_3.jpg',
            'i1778357108502_1298_0_5.jpg'
        ],
        desc: ''
    },
    41: {
        images: [
            'i1777235492894_9025_0_0.jpg',
            'i1777235492894_9621_0_5.jpg',
            'i1777235492895_6229_0_1.jpg',
            'i1778429706858_3459_0_7.jpg',
            'i1778429731070_2118_0_7.jpg',
            'i1778429744958_5948_0_7.jpg',
            'i1778429759682_809_0_4.jpg'
        ],
        desc: '$88\nStylish Men\'s and Women\'s Matching Shoes: 1906 Series—Breathable, Lightweight Sneakers for Sports, Travel, Running, and Jogging with a Fresh, Casual Look'
    },
    42: {
        images: [
            'i1778429759683_4860_0_3.jpg',
            'i1778429759683_5866_0_0.jpg',
            'i1778429759683_6436_0_8.jpg',
            'i1778429759684_5299_0_2.jpg',
            'i1778429760075_2790_0_6.jpg',
            'i1778429760076_1918_0_5.jpg',
            'i1778429760077_5054_0_1.jpg',
            'i1778429760078_5818_0_7.jpg'
        ],
        desc: '$85\nAuthentic 1906 Dad Sneakers for Men and Women – The Same Style Worn by Jeon Ji-hyun: Breathable Casual Running Shoes for Fall/Winter'
    },
    43: {
        images: [
            'i1777235492894_9117_0_4.jpg',
            'i1778429771885_6531_0_7.jpg',
            'i1778429785084_5625_0_7.jpg',
            'i1778429816925_842_0_3.jpg',
            'i1778429816930_1775_0_6.jpg',
            'i1778429816934_3602_0_4.jpg',
            'i1778429816935_5282_0_5.jpg',
            'i1778429817296_644_0_1.jpg',
            'i1778429817531_5912_0_0.jpg',
            'i1778429817531_846_0_2.jpg'
        ],
        desc: '$88\nTrending Authentic N1906R Deconstructed Retro Low-Top Unisex Versatile Commuter Running Shoes with Breathable Mesh Upper'
    },
    44: {
        images: [
            'i1778429900738_2482_0_3.jpg',
            'i1778429900738_254_0_0.jpg',
            'i1778429900738_4385_0_7.jpg',
            'i1778429900739_1427_0_5.jpg',
            'i1778429900739_757_0_8.jpg',
            'i1778429901575_9915_0_1.jpg',
            'i1778429901578_8844_0_2.jpg',
            'i1778429901579_2252_0_4.jpg',
            'i1778429901579_8248_0_6.jpg'
        ],
        desc: '$88\nAdidas Men\'s Running Shoes 2026 Early Summer New Arrival: Comfortable and Stylish Sports Shoes JR7410'
    },
    45: {
        images: [
            'i1778429990027_3326_0_2.jpg',
            'i1778429990027_4632_0_5.jpg',
            'i1778429990027_4814_0_3.jpg',
            'i1778429990028_5056_0_1.jpg',
            'i1778429990028_7493_0_6.jpg',
            'i1778429990712_3018_0_7.jpg',
            'i1778429990713_2719_0_4.jpg',
            'i1778429990726_4349_0_0.jpg',
            'i1778429990726_9187_0_8.jpg'
        ],
        desc: '$85\nHigh-Top Ghost Classic Tiger Beige and Blue Retro Sneakers: Breathable Slip-On Couple\'s Shoes for Men and Women'
    },
    46: {
        images: [
            'i1778431872204_6727_0_0.jpg',
            'i1778431872205_8577_0_2.jpg',
            'i1778431872206_1636_0_1.jpg',
            'i1778431872206_7579_0_6.jpg',
            'i1778431872207_4885_0_3.jpg',
            'i1778431873039_4664_0_4.jpg',
            'i1778431873042_3553_0_8.jpg',
            'i1778431873043_8674_0_7.jpg',
            'i1778431873046_4055_0_5.jpg'
        ],
        desc: '$88\n[Custom] Authentic Nike Desert Dunes Couple\'s Set: Distressed, Trendy Spring/Fall Commuter, Running, and Casual Shoes'
    },
    47: {
        images: [
            'i1778432081571_9785_0_0.jpg',
            'i1778432082913_6271_0_4.jpg',
            'i1778432082916_2483_0_7.jpg',
            'i1778432100403_8579_0_4.jpg',
            'i1778432100403_899_0_7.jpg',
            'i1778432101320_5765_0_0.jpg'
        ],
        desc: '$88\nSpring & Autumn Training Network: Lightweight Structure Plus Ultra-Lightweight Outdoor Cushioned Casual Athletic Breathable Running Shoes'
    },
    48: {
        images: [
            'i1778432446481_1043_0_0.jpg',
            'i1778432446482_1338_0_1.jpg',
            'i1778432446483_2733_0_4.jpg',
            'i1778432446483_7134_0_6.jpg',
            'i1778432446483_8303_0_8.jpg',
            'i1778432447408_3531_0_5.jpg',
            'i1778432447410_8769_0_2.jpg',
            'i1778432447412_3890_0_3.jpg',
            'i1778432447413_1465_0_7.jpg'
        ],
        desc: '$85\nNew Summer Printed Flat Sneakers for Men and Women: Trendy, Affordable, Low-Top Casual Skate Shoes for Couples'
    },
    49: {
        images: [
            'i1778440212088_5013_0_0.jpg',
            'i1778440212088_5204_0_3.jpg',
            'i1778440212088_6312_0_1.jpg',
            'i1778440213236_5300_0_5.jpg',
            'i1778440213239_7973_0_4.jpg',
            'i1778440213247_2059_0_2.jpg'
        ],
        desc: '$88\nadidas Comfortable, Versatile, Shock-Absorbing, Durable Low-Top Sneakers IG4338'
    },
    50: {
        images: [
            'i1778442765994_1340_0_3.jpg',
            'i1778442765994_182_0_8.jpg',
            'i1778442767135_243_0_7.jpg',
            'i1778442767136_235_0_0.jpg',
            'i1778442767137_631_0_2.jpg',
            'i1778442768297_7232_0_4.jpg',
            'i1778442768305_8000_0_1.jpg',
            'i1778442768310_7309_0_5.jpg'
        ],
        desc: '$85\nVomeroPlusrun Ultra-Lightweight Women\'s Running Shoes: Cushioned, Breathable, and Stylish HV8154 606'
    },
    51: {
        images: [
            'i1778522358254_225_0_3.jpg',
            'i1778522358254_5520_0_7.jpg',
            'i1778522358254_7864_0_4.jpg',
            'i1778522358256_9604_0_1.jpg',
            'i1778522358258_7104_0_6.jpg',
            'i1778522359291_3118_0_8.jpg',
            'i1778522359292_2038_0_2.jpg',
            'i1778522359295_2970_0_5.jpg',
            'i1778522359295_9058_0_0.jpg'
        ],
        desc: '$85\nNIKE 2026 Summer New Arrival: Dunk Low Sneakers—Low-Top, Lightweight, Cushioned IM6572-002'
    },
    52: {
        images: [
            'i1778522448398_830_0_4.jpg',
            'i1778522482671_9825_0_4.jpg',
            'i1778522523148_9394_0_4.jpg',
            'i1778522609626_7649_0_4.jpg',
            'i1778522637001_7080_0_4.jpg',
            'i1778522659516_9471_0_4.jpg',
            'i1778522681477_3587_0_4.jpg',
            'i1778522703700_2702_0_4.jpg'
        ],
        desc: '$85\nHiroshi Fujiwara x Mind 001 Unisex Comfortable and Soft Recovery Sports Slippers—Stylish and Massaging, Perfect for Everyday Wear'
    },
    53: {
        images: [
            'i1778523713971_6515_0_7.jpg',
            'i1778523713972_4863_0_1.jpg',
            'i1778523713972_5546_0_5.jpg',
            'i1778523715580_6495_0_8.jpg',
            'i1778523715582_7365_0_3.jpg',
            'i1778523715583_2862_0_6.jpg',
            'i1778523717200_2012_0_2.jpg',
            'i1778523717202_3805_0_0.jpg',
            'i1778523717203_2676_0_4.jpg'
        ],
        desc: '$85\n[High-Top Sneakers] New Black and Blue Printed Couple\'s Casual Sneakers for Men and Women: Light Luxury, Durable, and Stylish'
    },
    54: {
        images: [
            'i1778597414276_164_0_4.jpg',
            'i1778597414277_6177_0_1.jpg',
            'i1778597414277_8259_0_2.jpg',
            'i1778597414277_8963_0_9.jpg',
            'i1778597414278_1934_0_8.jpg',
            'i1778597414837_9210_0_3.jpg',
            'i1778597414838_3089_0_5.jpg',
            'i1778597414839_3146_0_6.jpg',
            'i1778597414840_5661_0_7.jpg'
        ],
        desc: '$88\nAJ1 Reverse Swoosh Snake Year White/Red Putian Bestseller: Versatile Low-Top Stylish Sneakers for Men and Women—Casual, Sporty, and Perfect for Couples'
    },
    55: {
        images: [
            'i1778601462983_970_0_7.jpg',
            'i1778601476028_2549_0_7.jpg',
            'i1778601493609_4072_0_7.jpg',
            'i1778601511920_4966_0_7.jpg',
            'i1778601530563_6169_0_7.jpg',
            'i1778601548419_1681_0_7.jpg',
            'i1778601563967_5590_0_7.jpg',
            'i1778601580600_7651_0_7.jpg',
            'i1778601602417_1765_0_7.jpg'
        ],
        desc: '$88\nKahana 8: This Fall\'s Best-Selling Retro Casual Hiking “Dad” Sneakers for Men and Women—Breathable, Comfortable, and Perfect for Outdoor Activities (With Laces)'
    },
    56: {
        images: [
            'i1778603147476_9774_0_5.jpg',
            'i1778603147477_4097_0_1.jpg',
            'i1778603147478_173_0_3.jpg',
            'i1778603147479_3899_0_8.jpg',
            'i1778603147535_5351_0_0.jpg',
            'i1778603151531_1162_0_2.jpg',
            'i1778603151532_5461_0_4.jpg',
            'i1778603151534_1381_0_6.jpg',
            'i1778603151534_6090_0_7.jpg'
        ],
        desc: '$85\nNike Women\'s Dunk Low Retro Yellow/White Suede Sneakers IB4417-101'
    },
    57: {
        images: [
            'i1778603518118_7978_0_0.jpg',
            'i1778603518122_5245_0_4.jpg',
            'i1778603518122_7784_0_5.jpg',
            'i1778603518123_1783_0_1.jpg',
            'i1778603518123_6137_0_2.jpg',
            'i1778603519503_603_0_6.jpg',
            'i1778603519504_1644_0_8.jpg',
            'i1778603519506_5795_0_7.jpg',
            'i1778603519507_1613_0_3.jpg'
        ],
        desc: '$88\nTrendy, Versatile, Two-Tone Low-Top Leather Sneakers for Men and Women: Ghost Tiger White, Black, and Gold—a Viral Hit on Social Media'
    },
    58: {
        images: [
            'i1778604421651_1266_0_8.jpg',
            'i1778604421651_4765_0_3.jpg',
            'i1778604421651_5676_0_0.jpg',
            'i1778604421652_4863_0_1.jpg',
            'i1778604421652_7959_0_6.jpg',
            'i1778604423090_9948_0_5.jpg',
            'i1778604423092_2127_0_4.jpg',
            'i1778604423093_2567_0_2.jpg',
            'i1778604423093_5642_0_7.jpg'
        ],
        desc: '$85\nAdidas Originals FORUM LOW: Comfortable and Versatile Low-Top Sneakers FY7755'
    },
    59: {
        images: [
            'i1778605481538_112_0_7.jpg',
            'i1778605481538_2329_0_8.jpg',
            'i1778605482560_9918_0_5.jpg',
            'i1778605482563_6388_0_1.jpg',
            'i1778605512824_296_0_7.jpg',
            'i1778605512824_8415_0_5.jpg',
            'i1778605512826_395_0_8.jpg',
            'i1778605513718_9402_0_1.jpg'
        ],
        desc: '$88\nBest-Selling Salo XTQ Unisex Outdoor Hiking Shoes: Non-Slip, Durable, Casual, Trail Running, and Mountaineering Shoes for Couples'
    },
    60: {
        images: [
            'i1778605602793_1203_0_4.jpg',
            'i1778605602793_1_0_6.jpg',
            'i1778605602793_5560_0_1.jpg',
            'i1778605602794_7113_0_3.jpg',
            'i1778605602794_7471_0_2.jpg',
            'i1778605603498_7013_0_5.jpg',
            'i1778605603502_3872_0_8.jpg',
            'i1778605603502_4099_0_7.jpg',
            'i1778605603502_4252_0_0.jpg'
        ],
        desc: '$88\nAdidas Women\'s Trefoil HANDBALL Casual Training Shoes, Leopard Print T-Strap KI667'
    },
    61: {
        images: [
            'i1778605748762_4693_0_7.jpg',
            'i1778605749877_921_0_1.jpg',
            'i1778605764834_4909_0_0.jpg',
            'i1778605764834_5952_0_7.jpg',
            'i1778605764834_6050_0_8.jpg',
            'i1778605764835_1383_0_3.jpg',
            'i1778605764836_6411_0_5.jpg',
            'i1778605765768_3061_0_6.jpg',
            'i1778605765771_236_0_2.jpg',
            'i1778605765771_6241_0_1.jpg',
            'i1778605765771_9135_0_4.jpg'
        ],
        desc: '$88\nAuthentic New Best-Selling AF1 Unisex Air Force 1 Campus Couple\'s Style Instagram-Ready Versatile Sports Fashion Casual Sneakers'
    },
    62: {
        images: [
            'i1778606861866_8215_0_2.jpg',
            'i1778606861868_541_0_1.jpg',
            'i1778606861869_6852_0_7.jpg',
            'i1778606861869_7620_0_0.jpg',
            'i1778606861869_8544_0_6.jpg',
            'i1778606862768_4675_0_5.jpg',
            'i1778606862768_8584_0_8.jpg',
            'i1778606862769_6869_0_3.jpg',
            'i1778606862770_2311_0_4.jpg'
        ],
        desc: '$88\nAdidas Trefoil Sneakers for Men and Women: New Fall/Winter FORUM Low-Top Sneakers—Breathable Casual Shoes'
    },
    63: {
        images: [
            'i1778607193321_2414_0_4.jpg',
            'i1778607193321_8883_0_0.jpg',
            'i1778607193322_3245_0_6.jpg',
            'i1778607193322_9859_0_5.jpg',
            'i1778607193323_6611_0_8.jpg',
            'i1778607194005_9784_0_2.jpg',
            'i1778607194006_6901_0_7.jpg',
            'i1778607194006_8159_0_1.jpg',
            'i1778607194033_1603_0_3.jpg'
        ],
        desc: '$85\nMETASPEED SKY TOKYO Racing Carbon Mesh Marathon Running Shoes with Full-Length Cushioning'
    },
    64: {
        images: [
            'i1778607603420_6506_0_3.jpg',
            'i1778607603420_6855_0_5.jpg',
            'i1778607603420_7496_0_1.jpg',
            'i1778607605374_6130_0_7.jpg',
            'i1778607605374_7954_0_2.jpg',
            'i1778607605375_7847_0_0.jpg',
            'i1778607607028_3521_0_6.jpg',
            'i1778607607029_1204_0_4.jpg',
            'i1778607607030_309_0_8.jpg'
        ],
        desc: '$88\nAirZoom AlphaFly NEXT% Men\'s and Women\'s Marathon Running Shoes with Air Cushioning, Lightweight and Slim Fit DV9425-300'
    },
    65: {
        images: [
            'i1778607875028_2738_0_8.jpg',
            'i1778607875029_7850_0_4.jpg',
            'i1778607875029_7977_0_5.jpg',
            'i1778607875030_1138_0_1.jpg',
            'i1778607875030_6791_0_7.jpg',
            'i1778607876099_957_0_6.jpg',
            'i1778607876100_7029_0_2.jpg',
            'i1778607876104_4166_0_0.jpg',
            'i1778607876105_4597_0_3.jpg'
        ],
        desc: '$85\nNike Men\'s Running Shoes: 2026 Summer New Arrival PEGASUS 42 Breathable Mesh Sneakers'
    },
    66: {
        images: [
            'i1778611874306_1631_0_5.jpg',
            'i1778611874307_6913_0_2.jpg',
            'i1778611874307_7696_0_6.jpg',
            'i1778611875744_5496_0_4.jpg',
            'i1778611875747_8985_0_3.jpg',
            'i1778611875752_2062_0_0.jpg',
            'i1778611876805_8545_0_8.jpg',
            'i1778611876809_4942_0_1.jpg',
            'i1778611876817_2322_0_7.jpg'
        ],
        desc: '$85\nAuthentic 2026 New Model Waterproof EvoSLATR Marathon Versatile Running Shoes for Men and Women: Casual, Training, and Racing'
    },
    67: {
        images: [
            'i1778612485312_1884_0_5.jpg',
            'i1778612485312_4336_0_1.jpg',
            'i1778612485313_9392_0_3.jpg',
            'i1778612487699_7641_0_7.jpg',
            'i1778612487704_2228_0_2.jpg',
            'i1778612487707_9638_0_0.jpg',
            'i1778612489040_7963_0_8.jpg',
            'i1778612489045_8458_0_4.jpg',
            'i1778612489050_3630_0_6.jpg',
            'i1778612865924_9135_0_7.jpg'
        ],
        desc: '$88\nNew Best-Selling Breathable Running Shoes: Comfortable, Lightweight, Versatile, Collaborative Edition for Men and Women'
    },
    68: {
        images: [
            'i1778612865925_1324_0_8.jpg',
            'i1778612865925_425_0_6.jpg',
            'i1778612868318_1778_0_3.jpg',
            'i1778612868323_6149_0_1.jpg',
            'i1778612868324_5725_0_0.jpg',
            'i1778612869544_118_0_2.jpg',
            'i1778612869544_5848_0_5.jpg',
            'i1778612869544_8443_0_4.jpg'
        ],
        desc: '$85\nNew Spring Men\'s Skate Shoes AF1FK2-WPP Casual Shoes AV3042-100: Breathable, Durable Flyknit Skate Shoes'
    },
    69: {
        images: [
            'i1778682747903_5270_0_0.jpg',
            'i1778682747904_1017_0_5.jpg',
            'i1778682749455_241_0_8.jpg',
            'i1778682776659_4463_0_8.jpg',
            'i1778682778195_8470_0_0.jpg',
            'i1778682788637_2382_0_8.jpg',
            'i1778682788637_3707_0_0.jpg',
            'i1778682801058_7075_0_8.jpg',
            'i1778682802701_6053_0_0.jpg'
        ],
        desc: '$88\nMLB Shoes: Unisex Couple\'s Checkered Retro Sneakers, Casual Chunky-Soled Sneakers, Spring/Summer 2026 New Arrival 3ASXM046N'
    },
    70: {
        images: [
            'i1778699755770_4131_0_3.jpg',
            'i1778699755774_4073_0_4.jpg',
            'i1778699755789_7936_0_1.jpg',
            'i1778699756366_7895_0_5.jpg',
            'i1778699756367_480_0_2.jpg',
            'i1778699756370_5205_0_0.jpg'
        ],
        desc: '$88\nNew TOKYODECONPACK Limited Edition Sneakers: Versatile, Trendy, and Casual for Men and Women—Thin-Soled Training Shoes'
    },
    71: {
        images: [
            'i1778774233585_4608_0_8.jpg',
            'i1778774233587_596_0_7.jpg',
            'i1778774234870_3058_0_1.jpg',
            'i1778774234871_6293_0_5.jpg',
            'i1778774254954_4305_0_5.jpg',
            'i1778774254954_7765_0_8.jpg',
            'i1778774254956_8026_0_7.jpg',
            'i1778774255817_311_0_1.jpg',
            'i1778775033928_7070_0_7.jpg',
            'i1778775052797_4388_0_7.jpg',
            'i1778775068174_1313_0_7.jpg',
            'i1778775086788_5048_0_7.jpg',
            'i1778775114466_8837_0_7.jpg',
            'i1778775283793_8795_0_7.jpg'
        ],
        desc: '$85\nAJ1 Purple, Black, and White: Affordable Luxury Low-Top Unisex Fashionable and Versatile Sneakers for Casual, Sports, and Basketball – 553558-154'
    },
    72: {
        images: [
            'i1778775196019_2333_0_2.jpg',
            'i1778775196019_4381_0_4.jpg',
            'i1778775196020_5896_0_3.jpg',
            'i1778775196026_1903_0_7.jpg',
            'i1778775196026_5674_0_0.jpg',
            'i1778775196774_4580_0_5.jpg',
            'i1778775196775_2907_0_6.jpg',
            'i1778775196775_755_0_8.jpg',
            'i1778775196775_8189_0_1.jpg'
        ],
        desc: '$88\n2026 New Valentine\'s Day Limited Edition Classic Shell-Toe Low-Top Trendy Casual Durable Versatile Student Sneakers'
    },
    73: {
        images: [
            'i1778776224783_3135_0_0.jpg',
            'i1778776224784_7535_0_4.jpg',
            'i1778776224788_6411_0_7.jpg',
            'i1778776252427_3867_0_4.jpg',
            'i1778776252429_1105_0_0.jpg',
            'i1778776253328_1290_0_7.jpg',
            'i1778776264558_9535_0_7.jpg',
            'i1778776265444_3371_0_0.jpg',
            'i1778776265448_6532_0_4.jpg'
        ],
        desc: '$85\nNew Puma VOMERO 19 Cushioned Professional Running Shoes: Reflective Road Running Shoes, Lightweight and Slip-Resistant'
    },
    74: {
        images: [
            'i1778776716940_2651_0_7.jpg',
            'i1778776751793_877_0_7.jpg',
            'i1778776767778_9931_0_7.jpg',
            'i1778776782475_2863_0_7.jpg',
            'i1778776813157_7772_0_2.jpg',
            'i1778776813158_2434_0_4.jpg',
            'i1778776813158_8161_0_7.jpg',
            'i1778776813159_4630_0_1.jpg',
            'i1778776813159_897_0_8.jpg',
            'i1778776814048_2978_0_5.jpg',
            'i1778776814048_5039_0_3.jpg',
            'i1778776814048_5753_0_6.jpg',
            'i1778776814048_6823_0_0.jpg'
        ],
        desc: '$88\n2026 New Salo XT6 Men\'s Shoes: Authentic, Non-Slip, Shock-Absorbing, Casual, Lightweight, Breathable, Off-Road, Sports, and Hiking Shoes for Women'
    },
    75: {
        images: [
            'i1778777195362_5458_0_8.jpg',
            'i1778777195362_8597_0_0.jpg',
            'i1778777195363_6756_0_2.jpg',
            'i1778777195366_1774_0_1.jpg',
            'i1778777196352_8735_0_7.jpg',
            'i1778777196353_5055_0_4.jpg',
            'i1778777196353_6302_0_3.jpg'
        ],
        desc: '$85\nNew Authentic Yankees NY High-Top Sneakers: Height-Enhancing Retro Chunky-Sole Sports Shoes for Men and Women—Comfortable and Versatile'
    },
    76: {
        images: [
            'i1778778158929_411_0_4.jpg',
            'i1778778158931_5630_0_1.jpg',
            'i1778778158932_2796_0_7.jpg',
            'i1778778158932_387_0_2.jpg',
            'i1778778158932_4521_0_0.jpg',
            'i1778778159981_2996_0_3.jpg',
            'i1778778159982_5973_0_8.jpg',
            'i1778778159983_4903_0_6.jpg',
            'i1778778159983_9307_0_5.jpg'
        ],
        desc: '$85\nNIKE Men\'s Pegasus TRAIL 5 GORE-TEX Outdoor Shoes, Water-Resistant Running Shoes FQ0908-014'
    },
    77: {
        images: [
            'i1778780045630_5823_0_6.jpg',
            'i1778780045631_545_0_4.jpg',
            'i1778780045632_8924_0_7.jpg',
            'i1778780046615_8949_0_5.jpg',
            'i1778780046615_9982_0_3.jpg',
            'i1778780046616_3640_0_1.jpg',
            'i1778780048762_2935_0_2.jpg',
            'i1778780048763_1989_0_0.jpg',
            'i1778780048763_2189_0_8.jpg'
        ],
        desc: '$88\n2026 Women\'s Butterfly-Style Shoes: Classic Retro Chunky-Soled, Height-Enhancing, Breathable Mesh Casual Sneakers KI0557'
    },
    78: {
        images: [
            'o_1jlsfqbt0p3ffkeh1e1ppghhi0.jpeg',
            'o_1jlsfqbt11sgj1insddb1kru1fb04.jpeg',
            'o_1jlsfqbt11tkno1e14ou167oehc2.jpeg',
            'o_1jlsfqbt19o3mt14t11r4hqsu1.jpeg',
            'o_1jlsfqbt214fa1bht1dkd1qmo1kkk5.jpeg',
            'o_1jlsfqbt21knu1f021kgee2s61r7.jpeg',
            'o_1jlsfqbt2l2n181viqi103n11j26.jpeg',
            'o_1jlsfqbt31j3au3tursf7k1s4g9.jpeg',
            'o_1jlsfqbt31jn0h014jg1sdu11078.jpeg',
            'o_1jlsfqbt31p9147dn84fkn5hda.jpeg',
            'o_1jlsfrd0hicqovh175m1b4an8tb.jpeg'
        ],
        desc: '$88\n2026 Spring Best-Sellers: Retro Men\'s Shoes, Mesh, New Chinese-Style, Trendy Brand, Dad Shoes, Summer Chunky-Soled, Unisex, Breathable Casual Shoes'
    },
    79: {
        images: [
            'o_1jm16l7ms17qpa761ekm1pe8ava0.jpeg',
            'o_1jm16l7mu1j5i14up4l919dmhbj1.jpeg',
            'o_1jm16l7mvus9184c17r1lib5rq2.jpeg',
            'o_1jm16l7n016i9lj618ok15td12ug3.jpeg',
            'o_1jm16l7n11ima1tjql0f19uksn4.jpeg',
            'o_1jm16l7n31bfm1r6t1lfi4oi131b5.jpeg',
            'o_1jm16l7n5kl31tcpfmo6h91sue6.jpeg',
            'o_1jm16l7n6gak1g2bpbo17mk1u797.jpeg',
            'o_1jm16l7n71el01g31097ipgjao8.jpeg',
            'o_1jnv112091uqt1ji2llh1i0m47g0.jpeg',
            'o_1jnv129ta172l1hh41jplntq1jh1.jpeg',
            'o_1jnv12tjr1ih63g7fqt1u1e19542.jpeg',
            'o_1jnv133ld8ah141arpmmqd1unn3.jpeg'
        ],
        desc: '$85\n2026 New Arrival: Unisex Low-Top Casual Sneakers – CLASSI Retro Skate Shoes: Durable and Slip-Resistant'
    },
    100: {
        images: [
            '01.jpg',
            '1.jpg',
            '133.jpg',
            '2.jpg',
            'a1755122293181_4067.jpg',
            'a1755122293188_3444.jpg',
            'a1755122293189_1780.jpg',
            'a1755122293202_8868.jpg',
            'a1755122299817_6861.jpg',
            'a1755122299818_3126.jpg',
            'a1755122299822_8362.jpg',
            'a1755122304896_5655.jpg',
            'a1759388138173_1634.jpg',
            'a1759471700314_5454.jpg'
        ],
        desc: '$85\n2026 Spring New Arrival: V5 RNR Millennium Versatile Running Shoes – Unisex Retro-Style Elevated Breathable Sneakers'
    },
    101: {
        images: [
            'i1778008531509_1130_0_1.jpg',
            'i1778008531509_5095_0_2.jpg',
            'i1778008531510_8229_0_4.jpg',
            'i1778008532669_5692_0_3.jpg',
            'i1778008532678_4744_0_7.jpg',
            'i1778008532680_2528_0_0.jpg',
            'i1778008533946_9665_0_8.jpg',
            'i1778008533953_8846_0_5.jpg',
            'i1778008533959_7910_0_6.jpg'
        ],
        desc: '$85\nNike Men\'s and Women\'s Winter Lightweight Flat-Soled Sneakers: DUNK Retro Sneakers with Rubber Soles IB4417-102'
    },
    102: {
        images: [
            '22.jpg',
            '33.jpg',
            'i1778010725980_1004_0_0.jpg',
            'i1778010904728_7081_0_0.jpg',
            'i1778011634889_4057_0_0.jpg',
            'i1778011636009_7339_0_1.jpg'
        ],
        desc: '$85\nAuthentic Dunk Low-Top Blue: Durable, Versatile, and Stylish—Trendy Casual Sneakers for Men and Women'
    },
    103: {
        images: [
            '素材4.jpg',
            '素材40.jpg',
            '素材41.jpg'
        ],
        desc: '$88\nCloud Star-Inspired Hole-Patterned Sandals for Women: New Summer Style with Elevated Heels, Thick Soles, Non-Slip Beach-Ready, Round-Toe, Soft-Soled Flip-Flops'
    },
    104: {
        images: [
            '想11.jpg',
            '新10.jpg',
            '新12.jpg',
            '新13.jpg',
            '新14.jpg',
            '新15.jpg',
            '新7.jpg',
            '新8.jpg',
            '新9.jpg',
            '素材7.jpg',
            '素材70.jpg',
            '素材71.jpg',
            '素材72.jpg',
            '素材8.jpg'
        ],
        desc: '$85\nAuthentic Yankees-inspired “NY Dad” Chunky-Sole Retro Sneakers—Unisex Casual Height-Boosting Shoes for Couples'
    },
    105: {
        images: [
            '新1.jpg',
            '新2.jpg',
            '新3.jpg',
            '新4.jpg',
            '新5.jpg',
            '新6.jpg'
        ],
        desc: '$85\nNew P-6000 Gray Unisex Comfortable Retro Sneakers: Low-Top Couple\'s Casual Dad Shoes for Urban Running'
    },
    106: {
        images: [
            '新16.jpg',
            '新17.jpg',
            '新18.jpg',
            '新19.jpg',
            '新20.jpg',
            '新21.jpg',
            '新22.jpg',
            '新23.jpg',
            '新24.jpg'
        ],
        desc: '$85\nMLB Chunky-Soled All-Over Print Sneakers  Non-Slip, Durable, Height-Enhancing, Low-Top, Unisex, Pink'
    },
    107: {
        images: [
            '新25.jpg',
            '新26.jpg',
            '新27.jpg',
            '新28.jpg',
            '新29.jpg',
            '素材3.jpg',
            '素材5.jpg',
            '素材6.jpg'
        ],
        desc: '$85\nAuthentic Moon Pegasus 41 Fluorescent Green Campus-Style Ultra-Lightweight Running Shoes: Breathable, Versatile Casual Sneakers for Men and Women'
    },
    108: {
        images: [
            '新30.jpg',
            '新31.jpg',
            '新32.jpg',
            '新33.jpg',
            '新34.jpg',
            '新35.jpg',
            '新36.jpg',
            '新37.jpg',
            '素材1.jpg',
            '素材2.jpg'
        ],
        desc: '$85\nNew Pegasus W8 Running Shoes: Zoom Air Cushioning, Moon Landing Shock Absorption, Durable, High Rebound, Mesh Upper, Breathable, Sports Shoes'
    },
    109: {
        images: [
            '新38.jpg',
            '新39.jpg',
            '新40.jpg',
            '新41.jpg',
            '新42.jpg',
            '新43.jpg',
            '新44.jpg'
        ],
        desc: '$85\nCssic Best-Seller Gel K8 Series Retro Running Shoes: Breathable and Non-Slip KAHANA Men\'s and Women\'s FL Running Shoes'
    },
    110: {
        images: [
            '新45.jpg',
            '新46.jpg',
            '新47.jpg',
            '新48.jpg',
            '新49.jpg',
            '新50.jpg',
            '新51.jpg',
            '新52.jpg'
        ],
        desc: '$85\nKailash FUGA EX3 Outdoor Hiking and Trekking Shoes: Breathable, Lightweight Trail Running Shoes KS2513108'
    },
    111: {
        images: [
            '新53.jpg',
            '新54.jpg',
            '新55.jpg',
            '新56.jpg',
            '新57.jpg',
            '新58.jpg',
            '新59.jpg',
            '新60.jpg'
        ],
        desc: '$88\nNike Men\'s Outdoor Sneakers NIKE ACG MOUNTAIN FLY LOW GORE-TEX IQ9789-062'
    },
    112: {
        images: [
            'S5.jpg',
            'S6.jpg',
            'S7.jpg',
            'S8.jpg',
            'i1778767909726_2458_0_7.jpg',
            's1.jpg',
            's3.jpg',
            's4.jpg'
        ],
        desc: '$85 MLB CHUNKY LINER DENIM: Trendy and Versatile, Chunky-Soled, Height-Enhancing, Comfortable Denim Casual Shoes, Slip-Resistant and Durable, Low-Top, Dad Shoes'
    },
    113: {
        images: [
            's1.jpg',
            's2.jpg',
            's3.jpg',
            's4.jpg'
        ],
        desc: '$70\n Adidas Originals Adimule: Comfortable, versatile, and durable slip-on sandals'
    },
    114: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg'
        ],
        desc: '$70 \nM-Size Authentic Nike Mind 001 Neuroscience Foot Massage Slippers'
    },
    115: {
        images: [
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg',
            'S7.jpg',
            'S8.jpg',
            'S9.jpg',
            's1.jpg'
        ],
        desc: '$70 \nNike Mind 001 Recovery Slide: Comfortable and Soft Nike Round-Toe Slides'
    },
    116: {
        images: [
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg',
            's1.jpg'
        ],
        desc: '$70 \nNike Mind 001 Neuroscience Foot Massage Slip-On Sandals\n\nNike × Fragment Design  Mind 001 Hiroshi Fujiwara Lightning⚡️ Collaboration'
    },
    117: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg',
            'S7.jpg',
            'S8.jpg',
            'S9.jpg'
        ],
        desc: '$70\n(10 deducted for missing accessories)\nTop-of-the-line Dongguan-made Crocs Classic Clog with all-over print, available in Smurf Blue and Winnie the Pooh designs\nSummer classic dual-purpose beach clogs, sandals, and flip-flops, packaged in a transparent waterproof bag'
    },
    118: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg',
            'S7.jpg'
        ],
        desc: '$55\n(10 deducted for missing accessories)\nTop-of-the-line Dongguan-made Crocs Classic Clogs with all-over prints, available in Smurf Blue and Winnie the Pooh designs\nSummer classics: dual-purpose beach clogs, sandals, and flip-flops, packaged in a transparent waterproof bag'
    },
    119: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg',
            'S7.jpg',
            'S8.jpg',
            'S9.jpg'
        ],
        desc: '$55\nAdidas Originals Adilette: Comfortable athletic rubber-soled flip-flops\nWith their casual, everyday style, the Adilette is the perfect companion for post-game relaxation and strolls on the beach. These flip-flops feature a lined, contoured footbed for a comfortable, snug fit, along with a single-strap upper adorned with a printed design created by the Brazilian brand FARM Rio.'
    },
    120: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg',
            'S7.jpg'
        ],
        desc: '$85\nCrocs Bella Clog EVA Comfortable and Versatile Clogs\nSummer-ready dual-purpose beach clogs, sandals, and flip-flops. Comes in a transparent waterproof bag. Please note: accessories must be purchased separately.\nCrafted from ultra-lightweight, patented Croslite material. The upper is more durable and easy to clean. Sizes: 35–40'
    },
    121: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg'
        ],
        desc: '$55\nOriginals AdiFOM SUPER STAR MULE\nAdidas Non-Slip, Durable, Lightweight, Open-Lace, Breathable Slippers\nLightweight and comfortable—slip them on and go—bringing a modern twist to classic style\nWith a chunky silhouette and ultra-smooth texture\nMade with foam containing sugarcane—committed to sustainability\nFree from the hassle of straps or laces—easy to slip on and off \nStay comfortable with natural, renewable materials\nDesigned to help reduce plastic pollution'
    },
    122: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg',
            'S7.jpg',
            'S8.jpg',
            'S9.jpg'
        ],
        desc: '$85\nMLB MOUNDER MONOGRAM SLIDE New York Yankees Summer Casual Slides MLB Slides Item No.: 3ALPSB053 Sizes: 36–40'
    },
    123: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg',
            'S7.jpg',
            'S8.jpg'
        ],
        desc: '$88\nBirkenstock Flip-Flops\nMade in Guangdong #Birkenstock, a renowned German footwear brand with over a century of history# Crafted from soft suede leather #Features a cushioned cork-rubber midsole and a unique footbed design that contours to the foot for superior comfort. The Birkenstock Milano is a classic unisex style with a cork sole that pairs well with any outfit. The sole is durable and wear-resistant, making it perfect for summer.\nSizes: 35-45 (runs one size large)'
    },
    124: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg'
        ],
        desc: '$80\nFig. 1: Women\'s sizes 36–41; other men\'s and women\'s sizes 36–45\nAdidas OZWAVE CLOG JR6756 Stable, Cushioned, and Springy Thick-Soled Dad Slippers\nChef Shoes Generation 2\nDS-289D'
    },
    125: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg',
            'S7.jpg',
            'S8.jpg',
            'S9.jpg'
        ],
        desc: '$50\nPUMA 2023 Summer Collection Soft-Soled Outdoor Casual Flip-Flops\nItem No.: 394213 04\nSizes: 35–40'
    },
    126: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S4.jpg',
            'S5.jpg',
            'S6.jpg',
            'S7.jpg',
            'S8.jpg',
            'S9.jpg'
        ],
        desc: '$80\nNY Yankees Limited Edition 🏈 x Korea Exclusive MLB\nMLB Summer Collection: High-Quality MLB Slippers from Korea\nVersatile, trendy couple\'s slippers.\nLightweight foam sole manufactured by the original factory #Eco-friendly composite odor-resistant material'
    },
    127: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg'
        ],
        desc: '$80\nMen\'s sizes 40–45\nAdidas SUPERSTAR Summer Casual Beach Flip-Flops: Comfortable, Lightweight, Sporty, Non-Slip, Trendy Perforated Sandals'
    },
    128: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S5.jpg',
            'S6.jpg'
        ],
        desc: '$85\nNew Arrival 🚀 Birkenstock Flip-Flops\nMade in Guangdong #Birkenstock, the renowned German footwear brand with over a century of history #Features soft suede leather #The midsole is made of shock-absorbing cork and rubber. Its unique footbed design conforms to the foot for superior comfort. The Birkenstock Milano is a classic unisex style with a cork sole that pairs well with any outfit. The sole is sturdy and durable, making it perfect for summer.\nSizes: 34-41 (runs one size large)'
    },
    129: {
        images: [
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S45.jpg',
            'S6.jpg',
            'S7.jpg'
        ],
        desc: '$50\nAdidas Originals Adilette: Comfortable athletic rubber-soled flip-flops\nWith their casual, everyday style, the Adilette is the perfect companion for post-game relaxation and strolls on the beach. These flip-flops feature a lined, contoured footbed for a comfortable, snug fit, along with a single-strap upper adorned with a printed design created by the Brazilian brand FARM Rio.'
    },
    130: {
        images: [
            'S.jpg',
            'S1.jpg',
            'S2.jpg',
            'S3.jpg',
            'S5.jpg',
            'S6.jpg',
            'S7.jpg',
            'S8.jpg',
            'S9.jpg'
        ],
        desc: '$45\nNIKE VICTORI ONE SLIDE Nike Flip-Flops – Summer Fashion Beach Sandals JXX\nSizes: 36, 37, 38, 39, 40, 41, 42, 43, 44, 45'
    },
    131: {
        images: [
            'S1.jpg',
            'S10.jpg',
            'S2.jpg',
            'S3.jpg',
            'S5.jpg',
            'S6.jpg',
            'S7.jpg',
            'S8.jpg',
            'S9.jpg'
        ],
        desc: '$85\nDESCENTE Lcing Nars \n\nVersatile, soft, and slip-resistant flip-flops \n\nThe midsole design provides enhanced support and comfort \n\nOne-piece upper with a thickened lining hugs the foot for a comfortable fit\n\nUnisex style, white'
    }
};

// Backward-compat alias (used by product-script.js)
const SHOE_MANIFEST = Object.fromEntries(
    Object.entries(SHOE_DATA).map(([id, data]) => [id, data.images])
);


// Sorted array of all shoe IDs (may have gaps, e.g. [1,2,3,5,7,...])
const SHOE_IDS = Object.keys(SHOE_DATA).map(Number).sort((a, b) => a - b);
const TOTAL_SHOES = SHOE_IDS.length;
