// ============================================================
// Nail Data — AUTO-GENERATED by generate-nail-data.js
// Generated: 2026-05-31T10:39:11.685Z
// Total designs: 93
// ============================================================
// To add new nail designs:
//   1. Create nails/{id}/ folder with images + {id}.txt
//   2. Run: node generate-nail-data.js
// ============================================================

const NAIL_DATA = {
    1: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Trending Gold-Plated Short Almond-Shaped Flower Nail Stickers with Rhinestones and Pearls'
    },
    2: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Popular in Europe and the U.S.: 3D Floral Mid-Length Nail Tips'
    },
    3: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trending Short Almond-Shaped 3D French Manicure Nail Tips with Rhinestones'
    },
    4: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'European and American Instagram-style 3D 3D nail tips, short style, skin-brightening yellow floral design with rhinestones, seashells, and pearls'
    },
    5: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg'
        ],
        desc: 'Spring Peach Blossom Cat-Eye Short Nail Tips with Blush Nails: Sensual Style with 3D Ombré and Hand-Applied Rhinestones'
    },
    6: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trending Shell and Starfish Nail Art Stickers: Instagram-Style, European and American-Inspired, Fresh and Whimsical, Ready-to-Wear, Handmade Nail Stickers'
    },
    7: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Hand-applied, hand-carved, short-style summer nails with a sweet and gentle aesthetic—a finished 3D manicure'
    },
    8: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Short Wearable Cat-Eye Almond Nail Stickers: Sweet Strawberry Nail Art for Instagram'
    },
    9: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Spring Peach Blossom Cat-Eye Short Nail Tips with Blush Nails: Sensual Style with 3D Ombré and Hand-Applied Rhinestones'
    },
    10: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Trendy Cat-Eye Clip-On Nails: Short, Handcrafted, High-End Look'
    },
    11: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Trending Wearable Nails: Sweet, Cute, and Sophisticated—Handcrafted Nail Art, Wearable Nail Tips, and False Nails'
    },
    12: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Halloween Collection: Western-Style Nail Stickers with a Sexy, Devilish Vibe – Handmade Nail Stickers for International Shipping'
    },
    13: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: '24-Piece Ocean Series Almond-Shaped Nail Tips with Pearl Accents'
    },
    14: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Summer Instagram-style Island-themed Nail Art: Handmade Nail Tips and Stickers'
    },
    15: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: '3D Gold-Plated European-Style Nail Art: Blush Nails, 3D Floral Nails, French Leopard Print Nails, Almond-Shaped Nails, False Nails, Nail Tips'
    },
    16: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'European and American-style short almond-shaped nail tips with 3D floral and polka dot designs, hand-applied rhinestones'
    },
    17: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Set of 24 Nail Stickers: Mid-Length 3D Leopard Print Nail Tips, Sexy Style Nail Tips, Artificial Nails'
    },
    18: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'European and American-style nail extensions, 3D French manicure nail tips, wholesale nail extensions, nail stickers, and false nails'
    },
    19: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Violet Gold-Plated 3D Floral Nail Stickers with Hand-Applied Rhinestones—Export-Grade Cross-Border Artificial Nails'
    },
    20: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'New Short Almond-Shaped 3D Floral Summer Hand-Applied Rhinestone Nail Tips'
    },
    21: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Valentine\'s Day Nail Art: 3D Floral Design, Skin-Brightening Manicure, Hand-Applied Rhinestones, False Nails, and Nail Tips'
    },
    22: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'New Short Almond-Shaped 3D Floral Summer Ocean-Themed Hand-Applied Rhinestone Nail Tips'
    },
    23: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Trending in Europe and the U.S.: 3D Floral and Starfish Resin Nail Art with Hand-Applied Rhinestones'
    },
    24: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Trending Summer Nail Tips: Short Almond-Shaped 3D Blueberry Bow Design—Fresh and Cute Nail Tips'
    },
    25: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Trending Short Nail Tips: Hand-Embellished with Rhinestones and Resin, 3D Floral Design—European and American-Style Cross-Border Nail Tips'
    },
    26: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trending Gold-Plated Short Almond-Shaped Flower Nail Stickers with Rhinestones and Pearls'
    },
    27: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Trending Nail Art: Cross-Border Blush-Colored Nail Tips with 3D Red Flowers for Valentine\'s Day'
    },
    28: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: '30-Piece Set of European-Style Gradient Floral Almond-Shaped Nail Tips: Ombré Cat-Eye Design for a Brightening Effect'
    },
    29: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'European and American Instagram-style 3D 3D nail tips, short style, skin-brightening yellow floral design with rhinestones, seashells, and pearls'
    },
    30: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Pink 3D floral nail tips with gold beads—flattering and elegant, with a blush-pink almond-shaped design'
    },
    31: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Best-Selling Gold-Plated Short Almond-Shaped 3D Pink Floral Blush Nail Tips'
    },
    32: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Best-Selling Gold-Plated Short Almond-Shaped 3D Pink Floral Blush Nail Tips'
    },
    33: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'European and American-style Almond-Shaped Nail Tips with 3D Floral Design and Seductive Red Pomegranate Color – In Stock'
    },
    34: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'European and American-style gold-plated nail tips in teal green with 3D shell-shaped almond-cut nails, featuring rhinestones and pearls'
    },
    35: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Best-Selling Gold-Plated Long Nail Tips with 3D Floral Design, Luxurious Cross with Rhinestones, and Leopard-Print Nail Tips'
    },
    36: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'European and American-Style Nail Tips: Blue Ocean 3D Floral Polka Dot Design with Hand-Applied Rhinestones and Blush Effect'
    },
    37: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Best-selling in Europe and the U.S.: Adhesive Nail Tips with Sweet and Edgy Floral Designs, Pearls, and Rhinestones; Almond-Shaped Blush-Colored False Nails'
    },
    38: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Gold-Plated Nail Tips: Light Luxury, High-End Look, Almond-Shaped Blush Nails (30 Pre-Made False Nails)'
    },
    39: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'European and American-Style Short Almond-Shaped Nail Tips: Summer Vacation 3D Starfish, Seashell, and Petal Designs'
    },
    40: {
        images: [
            '1.jpg',
            '2.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Trending Almond-Shaped Nail Tips: Sweet Summer Pink 3D Floral Design with Shells, Starfish, and Rhinestones'
    },
    41: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '7.jpg',
            '8.jpg'
        ],
        desc: '3D Almond-Shaped Short Cat-Eye Floral Blush Nail Tips with Rhinestones'
    },
    42: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Trendy Polka Dot Nail Tips: 3D Floral and Shell-Inspired French Manicure with Hand-Applied Rhinestones'
    },
    43: {
        images: [
            '1.jpg',
            '10.jpg',
            '11.jpg',
            '12.jpg',
            '13.jpg',
            '14.jpg',
            '15.jpg',
            '16.jpg',
            '17.jpg',
            '18.jpg',
            '19.jpg',
            '2.jpg',
            '20.jpg',
            '21.jpg',
            '22.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg',
            '8.jpg',
            '9.jpg'
        ],
        desc: 'Custom-made Valentine\'s Day Handmade Nail Tips: Heart-Shaped Floral Design with Rhinestones, Specifically Designed for European and American Styles'
    },
    44: {
        images: [
            '1.jpg',
            '10.jpg',
            '11.jpg',
            '12.jpg',
            '13.jpg',
            '14.jpg',
            '15.jpg',
            '16.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg',
            '8.jpg',
            '9.jpg'
        ],
        desc: 'Custom Diamond-Inspired Nail Art: Trending Handmade Nail Stickers, Nail Decals, and False Nails'
    },
    45: {
        images: [
            '1.jpg',
            '10.jpg',
            '11.jpg',
            '12.jpg',
            '13.jpg',
            '14.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg',
            '8.jpg',
            '9.jpg'
        ],
        desc: 'Custom-made wearable nails: Handcrafted 3D relief nail art; Valentine\'s Day wearable nail tips and false nails'
    },
    46: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trending Polka Dot 3D Floral Almond-Shaped Nail Tips with Shell Pearls and Gold-Plated French Manicure'
    },
    47: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Leopard-print nail art, 3D floral design, luxury blush-colored nails, hand-applied rhinestones, Western-style hot girl nail art'
    },
    48: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg'
        ],
        desc: '30-Piece 3D 3D Nail Art Set: Flowers, Ocean, Starfish, Shells, Pearls, Almond-Shaped Nail Tips'
    },
    49: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Valentine\'s Day Cat-Eye 3D Almond-Shaped Bow Gold-Plated Checkered Nail Tips (30 pcs)'
    },
    50: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'European and American-Style Gold-Plated Heart-Shaped Almond-Shaped Nail Tips: Short, Purple Ombre Cat-Eye Design with Handmade Bow'
    },
    51: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: '30-Piece Fall/Winter Full-Diamond Gilded Handmade Wearable Nail Set: 3D Floral and Leopard-Print Nail Extensions'
    },
    52: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Luxurious Gold-Plated Striped 3D Embossed Press-On Nails'
    },
    53: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'French Manicure Black Beveled Edges Hot Girl Style Wholesale Nail Tips with Heart-Shaped Rhinestones and Rhinestone Accents, Ready-to-Use Artificial Nails and Nail Stickers'
    },
    54: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg'
        ],
        desc: 'Best-Selling Red Velvet KT [Doudou Jia] Nail Tips: Sweet Short Cat-Eye Nail Tips, Handmade'
    },
    55: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'European and American-style 3D Peach Blossom French Manicure Removable Nail Tips: Sweet Long Tube Nails by PressOnNails'
    },
    56: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trending in Europe and the US: French Manicure, False Nails, and Nail Tips—Instagram-Style Nail Art with Stripes for an Elegant and Feminine Look'
    },
    57: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trending in Europe and the US: 3D Floral and Starfish Resin Nail Art with Hand-Applied Rhinestones'
    },
    58: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Instagram-style cat-eye clip-on nails with fine glitter and champagne-colored rhinestones; luxurious short clip-on nail tips'
    },
    59: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Best-Selling Gold-Plated Nail Tips (30 Pieces): Almond-Shaped, Luxurious Diamond-Patterned Bow Christmas Tree Nail Tips'
    },
    60: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Best-Selling Gold-Plated Christmas Nail Tips: 24-Piece Set of 3D Almond-Shaped Santa Claus Nail Tips'
    },
    61: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Best-selling European and American-style wearable nails: medium-to-long ladder design, hand-applied rhinestones, silver stickers'
    },
    62: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'New Arrival: Almond-Shaped, Purple, Hand-Applied Short French 3D Leopard-Print Starfish Pearl Nail Tips'
    },
    63: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: '30-Piece Set of Long Almond-Shaped Nail Tips: Handcrafted Premium 3D Maple Leaf Polka Dot Gradient Nail Tips'
    },
    64: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: '24-Piece Set of Gold-Plated Cat-Eye Almond-Shaped Nail Tips with Sweet Bows, Blush-Colored Flowers, and Floral Designs'
    },
    65: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Christmas Best-Seller: Handmade Almond-Shaped Nail Extensions with a Luxurious Look—Snowflake-Patterned Nail Art with Rhinestones and Bows'
    },
    66: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg',
            '8.jpg'
        ],
        desc: 'European and American Instagram-style 3D 3D nail tips, short style, skin-brightening yellow floral design with rhinestones, seashells, and pearls'
    },
    67: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trendy European and American-style Instagram-inspired long almond-shaped dark gold-plated false nails'
    },
    68: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg'
        ],
        desc: '30-Piece Set of Handmade Gold-Plated Nail Art Decals: Valentine\'s Day Cat-Eye, Bow, and Heart-Shaped Gemstone Nails'
    },
    69: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trending Nail Art: White French Tips with Bows and Pearls—Sweet European and American Style Long Tube Nails'
    },
    70: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Best-Selling Gold-Plated Long Nail Tips with 3D Floral Design, Luxurious Cross with Rhinestones, and Leopard-Print Nail Tips'
    },
    71: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'European and American-style Almond-Shaped Short Nail Tips: Handmade Floral Design with Rhinestones and Pearls—Sweet and Edgy Nail Art Tips'
    },
    72: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg'
        ],
        desc: 'Removable Cat-Eating-Fish Nail Stickers for Kids, Ages 7–15: DIY Nail Art for Children'
    },
    73: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg'
        ],
        desc: 'Cool White Moonlight Long Nail Tips: Luxurious Nail Tips (30 Pieces, Assorted Sizes, Strip Pack, Handmade Pre-made Nails)'
    },
    74: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trendy Polka Dot Handmade Nail Tips: Luxurious, Seductive Red Shade That Flatters Fair Skin—Diamond-Embedded Nail Tips'
    },
    75: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: '24-Piece Set of Hand-Strung Rhinestone Nail Tips: Elegant Bow and Flower Design, Long Tube-Shaped Nail Tips'
    },
    76: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: '3D Embossed Handmade Nail Tips: Luxurious Gold-Plated Emerald Green Almond-Shaped Fall-Inspired Nail Tips'
    },
    77: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg',
            '8.jpg',
            '9.jpg'
        ],
        desc: 'Delicate, Luxurious, and Sophisticated Nail Art: Ready-to-Wear Nail Tips, Pearl Nail Tips, and Artificial Nails'
    },
    78: {
        images: [
            '1.jpg',
            '10.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg',
            '8.jpg',
            '9.jpg'
        ],
        desc: 'Delicate, Luxurious, and Sophisticated Nail Art: Ready-to-Wear Nail Tips, Pearl Nail Tips, and Artificial Nails'
    },
    79: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Delicate, Luxurious, and Sophisticated Nail Art: Ready-to-Wear Nail Tips, Pearl Nail Tips, and Artificial Nails'
    },
    80: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Best-selling Imported Nail Tips: European & French-Style Short Striped Cat-Eye Gold-Plated Nails—Perfect for Dates and Parties (Removable)'
    },
    81: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'European and American-style premium nail art: solid orange-red crystal gel short nails with floral designs—vibrant and elegant, perfect for vacations and travel'
    },
    82: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trendy French-style press-on nails: simple and sweet red hearts with white accents, European and American style, removable'
    },
    83: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trendy 3D French Manicure with Ice-Transparent Floral Design: Versatile, European-Style, Removable Artificial Nails and Nail Stickers'
    },
    84: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Y2K 3D Butterfly Nail Tips: Sweet, Cool, and Edgy Wine-Red Nails—Unique, Sophisticated, and Removable'
    },
    85: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Trendy Semi-Handmade Short Clear Red-Brown Nail Tips with a Glossy Finish'
    },
    86: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'New Summer Collection: Ultra-flattering Toenails in a Cool, Edgy Black-and-Gold Colorway with a High-Gloss Mirror Finish—Elegant and Luxurious False Nails'
    },
    87: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Premium Wearable Nail Art: Chic, Short Teardrop-Shaped Imitation Pearls with Rhinestones—Instagram-Style, Lightly Luxurious False Nails'
    },
    88: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Spring/Summer Handmade Nail Art: Bow, Lace, Polka Dots, Retro, French, Instagram-worthy, Student-style, Girly Nail Stickers'
    },
    89: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: '2026\'s Must-Have Nail Tips: Luxurious, Sparkling, Handcrafted Cat-Eye Nails That Brighten Your Complexion—Ready-to-Wear Luxury False Nails'
    },
    90: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'Handmade Nail Tips: Solid-Color, Gold-Plated, Skin-Brightening Glitter Nails—Handcrafted Premium Quality'
    },
    91: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg'
        ],
        desc: 'New International Trade Nail Art: Pearl-Finish Nail Tips, Gradient “Hot Girl” Style, Seductive False Nails, Handmade Nail Tips'
    },
    92: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg'
        ],
        desc: 'Export-Grade Handmade Premium Dopamine-Style Short Teardrop French 3D Floral Design Artificial Nails'
    },
    93: {
        images: [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg'
        ],
        desc: '96-Piece Set of Trendy European and American-Style Nail Tips: A Luxurious 4-Color Assortment of Cat-Eye Almond-Shaped Nail Tips'
    }
};

// Sorted array of all nail IDs (may have gaps, e.g. [1,2,3,5,7,...])
const NAIL_IDS = Object.keys(NAIL_DATA).map(Number).sort((a, b) => a - b);
const TOTAL_NAILS = NAIL_IDS.length;
